name: Assign Issue

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  assign:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: takanome-dev/assign-issue-action@v2.3
        with:
          maintainers: 'abshk-jr,amarjeetkapoor1,brad,cliffordwolf,donbright,gsohler,justbuchanan,kintel,MichaelAtOz,MichaelPFrey,minad,nophead,pca006132,rcolyer,shaina7837,Sharma-Hrishabh,t-paul,tbharathchandra,thehans'
          days_until_unassign: 30
          block_assignment: false
          reminder_days: 7
          max_assignments: 12
          assigned_comment: |
            ### üéâ Issue Assignment Confirmation

            Hey @{{ handle }}, thanks for taking on this issue!

            This issue will be automatically unassigned if idle for **{{ total_days }} days**.

            <details>
            <summary>‚ÑπÔ∏è Important information</summary>

            - To prevent automatic unassignment, a maintainer can add the **{{{ pin_label }}}** label
            - You can unassign yourself at any time by commenting with `/unassign-me`
            - Updates and status reports are encouraged to show progress
            </details>
