name: Code Format Check

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Beautify:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
      run: |
        which sudo || ( apt update && apt install -y sudo )
        sudo -E apt update
        sudo -E apt -qq -y install clang-format

    - name: Run check
      id: check
      run: ./scripts/beautify.sh --check
      continue-on-error: true

    - name: Generate patch
      if: steps.check.outcome == 'failure'
      run: |
        cp -r . ${{ runner.temp }}/a
        cp -r . ${{ runner.temp }}/b
        cd ${{ runner.temp }}/b
        ./scripts/beautify.sh --all
        cd ${{ runner.temp }}
        diff -ruN a b | tee ${{ runner.temp }}/beautify.patch

    - name: Upload patch artifact
      if: steps.check.outcome == 'failure'
      uses: actions/upload-artifact@v5
      with:
        name: beautify-patch
        path: ${{ runner.temp }}/beautify.patch
