name: linux

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        include:
          - os: ubuntu-20.04
            distro: focal
            qt5default: true
          - os: ubuntu-22.04
            distro: kinetic
            qt5default: false

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: ./scripts/github-ci-linux-get-dependencies.sh ${{ matrix.distro }}
    - name: Dependency fixup
      run: sudo apt-get install gettext gcovr
    - name: Make Qt5 the default
      if: ${{ matrix.qt5default }}
      run: sudo apt-get install qt5-default
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Build and test
      run: ./scripts/github-ci.sh enable_python build test coverage
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Test Result Report (${{ matrix.os }})
        path: |
          b/Testing/Temporary/*_report.html
          b/Testing/Temporary/LastTest.log
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: Code Coverage Report (${{ matrix.os }})
        path: c/coverage*.html
