name: Linux Experimental Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        qt: [ qt5, qt6 ]
        exclude:
          - os: ubuntu-22.04
            # libqscintilla2-qt6-dev not packaged
            qt: qt6

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} ${{ matrix.qt }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
      run: |
        which sudo || apt install -y sudo
        sudo ./scripts/uni-get-dependencies.sh ${{ matrix.qt }}
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.13'
    - name: Install gcovr
      run: uv sync --project .github/ci/openscad-coverage
    - name: Build
      run: ./scripts/github-ci.sh experimental enable_python ${{ matrix.qt }} build
    - name: Test
      # This is a bit wonky to use github-ci as it is.
      # `test` runs ctest, `test_examples` sets a persistent flag for ctest to run a different "configuration".
      # So we're running the default tests (no specified configuration), then the example tests. Has to be in that order.
      # Finally coverage reports what code paths got executed.
      run: ./scripts/github-ci.sh test test_examples test coverage
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v7
      if: ${{ always() }}
      with:
        name: Test Result Report (${{ matrix.os }} ${{ matrix.qt }})
        path: |
          b/Testing/Temporary/*_report.html
          b/Testing/Temporary/LastTest.log
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v7
      with:
        name: Code Coverage Report (${{ matrix.os }} ${{ matrix.qt }})
        path: c/coverage*.html
