name: linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        same-kernel: [false]
        include:
          - os: ubuntu-18.04
            distro: bionic
            same-kernel: false
          - os: ubuntu-20.04
            distro: focal
            same-kernel: false
          - os: ubuntu-20.04
            distro: focal
            same-kernel: true

    runs-on: ${{ matrix.os }}

    name: "${{ matrix.os }} (same-kernel=${{ matrix.same-kernel }})"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: ./scripts/travis-ci-before-install-linux.sh ${{ matrix.distro }}
    - name: Dependency fixup
      run: sudo apt-get install qt5-default gettext gcovr
    - name: Build and test
      run: FAST_CSG_SAME_KERNEL=${{ matrix.same-kernel }} ./scripts/github-ci.sh build test coverage
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Test Result Report (${{ matrix.os }})
        path: |
          b/tests/Testing/Temporary/*_report.html
          b/tests/Testing/Temporary/LastTest.log
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: Code Coverage Report (${{ matrix.os }})
        path: c/coverage*.html
