name: macos-tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-11
    name: macos-11
    # If it's not done in 60 minutes, something is wrong.
    # Default is 6 hours, which is a bit long to wait.
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install Homebrew packages
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        ./scripts/macosx-build-homebrew.sh
    - name: Build OpenSCAD
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DEXPERIMENTAL=ON -DSNAPSHOT=ON
        export NUMCPU=$(($(sysctl -n hw.ncpu) * 3 / 2))
        make -j$NUMCPU
    - name: Run Test Suite
      run: |
        cd build/tests
        export NUMCPU=$(($(sysctl -n hw.ncpu) * 3 / 2))
        ctest -j$NUMCPU
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: Test Result Report (MacOS)
        path: |
          build/tests/Testing/Temporary/*_report.html
          build/tests/Testing/Temporary/LastTest.log
