name: Linux Release Tests

on:
  push:
    branches:
      - master
      - "*-non-experimental"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Non-experimental

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        which sudo || apt install -y sudo
        sudo ./scripts/uni-get-dependencies.sh qt6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.13'
    - name: Install gcovr
      run: uv sync --frozen --project .github/ci/openscad-coverage
    - name: Build and test
      run: ./scripts/github-ci.sh enable_python build test coverage
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v6
      if: ${{ always() }}
      with:
        name: Test Result Report (non-experimental)
        path: |
          b/Testing/Temporary/*_report.html
          b/Testing/Temporary/LastTest.log
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v6
      with:
        name: Code Coverage Report (non-experimental)
        path: c/coverage*.html
