name: OpenSCAD Stale bot
on:
  schedule:
    - cron: "10 * * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/stale@v10
        with:
          # Max number of operations per run
          operations-per-run: 10
          # Order to get issues/PRs
          ascending: true

          # ISSUES
          # Do not auto-close an issue if it is assigned to a milestone
          exempt-all-issue-milestones: true
          # Exempt feature requests
          exempt-issue-labels: "Type: Enhancement,Tag: Good First Issue"
          # Idle number of days before marking issues stale
          days-before-issue-stale: 360
          # Idle number of days before marking issues close after stale label
          days-before-issue-close: 60
          stale-issue-label: "Stalled"
          close-issue-label: "Idle-Closed"
          remove-issue-stale-when-updated: true
          stale-issue-message: "OpenSCAD bot: this issue is stale because it has been inactive for 360 days. It will be closed if no further activity occurs within 60 days."
          close-issue-message: "OpenSCAD bot: This issue was closed because it has been inactive for 60 days since being marked as Stalled."

          # PRs
          # Do not auto-close a PR if it is assigned to a milestone
          exempt-all-pr-milestones: true
          exempt-draft-pr: true
          # Idle number of days before marking PRs stale
          days-before-pr-stale: 120
          # Idle number of days before marking PRs close after stale label
          days-before-pr-close: 60
          stale-pr-label: "Stalled"
          close-pr-label: "Idle-Closed"
          remove-pr-stale-when-updated: true
          stale-pr-message: "OpenSCAD bot: this PR is stale because it has been open for 120 days with no activity. It will be closed if no further activity occurs within 60 days."
          close-pr-message: "OpenSCAD bot: This PR was closed because it has been inactive for 60 days since being marked as Stalled."
