name: Windows(msys2) Experimental Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    strategy:
      matrix:
        qt: [ qt5, qt6 ]
    runs-on: windows-latest
    name: windows-latest ${{ matrix.qt }}
    env:
      MSYS_DIR: 'C:/openscad'
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Get Date
        shell: bash
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
      - name: Setup (detached) tmate session if enabled
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true
      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2
        with:
          location: ${{ env.MSYS_DIR }}
          msystem: UCRT64
          update: false
          # setup-msys2 caches the downloaded packages
          # ... if you pass them with `install` or `pacboy`
          # We could do that if nobody needs to run the script.
          # Otherwise it's better to have a single source of truth.
      - name: Restore MSYS2 package cache
        id: restore
        uses: actions/cache/restore@v4
        with:
          path: '${{ env.MSYS_DIR }}/msys64/var/cache/pacman/pkg'
          # Caches are immutable. We use CACHE_DATE so cache gets refreshed once a day.
          # We don't use restore-keys because we don't prune old packages.
          # But you could.
          key: ${{ runner.os }}-msys2-pkg-cache-${{ matrix.qt }}-${{ hashFiles('scripts/msys2-install-dependencies.sh', '.github/workflows/windows.yml') }}-${{ env.CACHE_DATE }}
      - name: Manual MSYS2 Update
        shell: cmd # Run from Windows host to allow taskkill
        # This stuff copied from setup-msys2 update step.
        # If you move the package list out of the script into "Setup MSYS2 Environment"
        # then delete this step and set `update: true`.
        run: |
          echo "Updating packages (ignoring return code)..."
          msys2 -c "pacman -Syuu --overwrite '*' --noconfirm" || verify >nul

          echo "Replacing pacman config (ignoring return code)..."
          msys2 -c "mv -f /etc/pacman.conf.pacnew /etc/pacman.conf" || verify >nul

          echo "Killing remaining tasks..."
          taskkill /F /FI "MODULES eq msys-2.0.dll" || verify >nul

          echo "Final system upgrade..."
          msys2 -c "pacman -Syuu --overwrite '*' --noconfirm"
      - name: Install MSYS2 Dependencies
        run: |
          pwd
          ./scripts/msys2-install-dependencies.sh ${{ matrix.qt }}
      - name: Save MSYS2 package cache
        id: save
        uses: actions/cache/save@v4
        # Only run if the cache was NOT found during restore to avoid "Cache already exists" warning.
        if: ${{ steps.restore.outputs.cache-hit != 'true' }}
        with:
          path: '${{ env.MSYS_DIR }}/msys64/var/cache/pacman/pkg'
          key: ${{ steps.restore.outputs.cache-primary-key }}
      - name: Install Mesa
        uses: ssciwr/setup-mesa-dist-win@v2
        with:
          version: '22.1.7'
          build-type: 'release-mingw'
      - name: Build OpenSCAD
        run: |
          mkdir build && cd build
          cmake .. -G"Ninja" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DEXPERIMENTAL=ON -DSNAPSHOT=ON -DUSE_QT6=${{ matrix.qt == 'qt6' && 'ON' || 'OFF' }}
          cmake --build . -j4
          cmake --install . --prefix=.
      - name: Run Test Suite
        run: |
          cd build
          ctest -j4
      - name: Setup (detached) tmate session if enabled
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Upload Test Result Report
        uses: actions/upload-artifact@v5
        if: ${{ always() }}
        with:
          name: Test Result Report (Windows ${{ matrix.qt }})
          path: |
            build/Testing/Temporary/*_report.html
            build/Testing/Temporary/LastTest.log
